### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by QWp6t**
With this PR, installing from composer will only require the following...

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/senlin/ymbeseo"
        }
    ],
    "require": {
        "senlin/ymbeseo": "dev-master"
    }
```

### CODE REVIEW

**Comment by senlin** [comment]
Hi guys, thanks for all your input and sorry to reply so late. 

I'm on holiday with hardly any internet access. I will get back to all of this after Dec 14th. 

Cheers,
Piet

**Comment by senlin** [comment]
thanks @QWp6t

**Comment by senlin** [comment]
@QWp6t Back from my travels and getting back in the saddle, to be hionest I don't have experience with adding composer.json to plugins. Now when I try to activate the ymbeseo (developer branch) on my local install it fails. Any ideas?

**Comment by QWp6t** [comment]
I just took a look at it. Doesn't seem to have anything to do with composer. 

I'm able to activate both master and development branch, but the latter produces warning messages in the admin panel about plugin conflicts (I'm not running any of the conflicting plugins listed in `admin/class-plugin-conflict.php`) and the following error log...
```
[13-Dec-2015 14:38:46 UTC] PHP Warning:  fopen(/srv/www/example.com/current/web/app/plugins/1): failed to open stream: No such file or directory in /srv/www/example.com/current/web/wp/wp-includes/functions.php on line 4458
[13-Dec-2015 14:38:46 UTC] PHP Stack trace:
[13-Dec-2015 14:38:46 UTC] PHP   1. {main}() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:0
[13-Dec-2015 14:38:46 UTC] PHP   2. require() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:16
[13-Dec-2015 14:38:46 UTC] PHP   3. activate_plugin() /srv/www/example.com/current/web/wp/wp-admin/plugins.php:42
[13-Dec-2015 14:38:46 UTC] PHP   4. do_action() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:572
[13-Dec-2015 14:38:46 UTC] PHP   5. call_user_func_array:{/srv/www/example.com/current/web/wp/wp-includes/plugin.php:525}() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   6. YMBESEO_Plugin_Conflict::hook_check_for_plugin_conflicts() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   7. Yoast_Plugin_Conflict->check_plugin_conflicts() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-plugin-conflict.php:143
[13-Dec-2015 14:38:46 UTC] PHP   8. Yoast_Plugin_Conflict->set_error() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:146
[13-Dec-2015 14:38:46 UTC] PHP   9. Yoast_Plugin_Conflict->get_conflicting_plugins_as_string() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:159
[13-Dec-2015 14:38:46 UTC] PHP  10. YMBESEO_Utils::get_plugin_name() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:126
[13-Dec-2015 14:38:46 UTC] PHP  11. get_plugin_data() /srv/www/example.com/current/web/app/plugins/ymbeseo/inc/class-ymbeseo-utils.php:790
[13-Dec-2015 14:38:46 UTC] PHP  12. get_file_data() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:84
[13-Dec-2015 14:38:46 UTC] PHP  13. fopen() /srv/www/example.com/current/web/wp/wp-includes/functions.php:4458

[13-Dec-2015 14:38:46 UTC] PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /srv/www/example.com/current/web/wp/wp-includes/functions.php on line 4461
[13-Dec-2015 14:38:46 UTC] PHP Stack trace:
[13-Dec-2015 14:38:46 UTC] PHP   1. {main}() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:0
[13-Dec-2015 14:38:46 UTC] PHP   2. require() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:16
[13-Dec-2015 14:38:46 UTC] PHP   3. activate_plugin() /srv/www/example.com/current/web/wp/wp-admin/plugins.php:42
[13-Dec-2015 14:38:46 UTC] PHP   4. do_action() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:572
[13-Dec-2015 14:38:46 UTC] PHP   5. call_user_func_array:{/srv/www/example.com/current/web/wp/wp-includes/plugin.php:525}() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   6. YMBESEO_Plugin_Conflict::hook_check_for_plugin_conflicts() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   7. Yoast_Plugin_Conflict->check_plugin_conflicts() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-plugin-conflict.php:143
[13-Dec-2015 14:38:46 UTC] PHP   8. Yoast_Plugin_Conflict->set_error() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:146
[13-Dec-2015 14:38:46 UTC] PHP   9. Yoast_Plugin_Conflict->get_conflicting_plugins_as_string() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:159
[13-Dec-2015 14:38:46 UTC] PHP  10. YMBESEO_Utils::get_plugin_name() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:126
[13-Dec-2015 14:38:46 UTC] PHP  11. get_plugin_data() /srv/www/example.com/current/web/app/plugins/ymbeseo/inc/class-ymbeseo-utils.php:790
[13-Dec-2015 14:38:46 UTC] PHP  12. get_file_data() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:84
[13-Dec-2015 14:38:46 UTC] PHP  13. fread() /srv/www/example.com/current/web/wp/wp-includes/functions.php:4461

[13-Dec-2015 14:38:46 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /srv/www/example.com/current/web/wp/wp-includes/functions.php on line 4464
[13-Dec-2015 14:38:46 UTC] PHP Stack trace:
[13-Dec-2015 14:38:46 UTC] PHP   1. {main}() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:0
[13-Dec-2015 14:38:46 UTC] PHP   2. require() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:16
[13-Dec-2015 14:38:46 UTC] PHP   3. activate_plugin() /srv/www/example.com/current/web/wp/wp-admin/plugins.php:42
[13-Dec-2015 14:38:46 UTC] PHP   4. do_action() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:572
[13-Dec-2015 14:38:46 UTC] PHP   5. call_user_func_array:{/srv/www/example.com/current/web/wp/wp-includes/plugin.php:525}() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   6. YMBESEO_Plugin_Conflict::hook_check_for_plugin_conflicts() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   7. Yoast_Plugin_Conflict->check_plugin_conflicts() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-plugin-conflict.php:143
[13-Dec-2015 14:38:46 UTC] PHP   8. Yoast_Plugin_Conflict->set_error() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:146
[13-Dec-2015 14:38:46 UTC] PHP   9. Yoast_Plugin_Conflict->get_conflicting_plugins_as_string() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:159
[13-Dec-2015 14:38:46 UTC] PHP  10. YMBESEO_Utils::get_plugin_name() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:126
[13-Dec-2015 14:38:46 UTC] PHP  11. get_plugin_data() /srv/www/example.com/current/web/app/plugins/ymbeseo/inc/class-ymbeseo-utils.php:790
[13-Dec-2015 14:38:46 UTC] PHP  12. get_file_data() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:84
[13-Dec-2015 14:38:46 UTC] PHP  13. fclose() /srv/www/example.com/current/web/wp/wp-includes/functions.php:4464

[13-Dec-2015 14:38:46 UTC] PHP Warning:  fopen(/srv/www/example.com/current/web/app/plugins/1): failed to open stream: No such file or directory in /srv/www/example.com/current/web/wp/wp-includes/functions.php on line 4458
[13-Dec-2015 14:38:46 UTC] PHP Stack trace:
[13-Dec-2015 14:38:46 UTC] PHP   1. {main}() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:0
[13-Dec-2015 14:38:46 UTC] PHP   2. require() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:16
[13-Dec-2015 14:38:46 UTC] PHP   3. activate_plugin() /srv/www/example.com/current/web/wp/wp-admin/plugins.php:42
[13-Dec-2015 14:38:46 UTC] PHP   4. do_action() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:572
[13-Dec-2015 14:38:46 UTC] PHP   5. call_user_func_array:{/srv/www/example.com/current/web/wp/wp-includes/plugin.php:525}() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   6. YMBESEO_Plugin_Conflict::hook_check_for_plugin_conflicts() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   7. Yoast_Plugin_Conflict->check_plugin_conflicts() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-plugin-conflict.php:143
[13-Dec-2015 14:38:46 UTC] PHP   8. Yoast_Plugin_Conflict->set_error() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:146
[13-Dec-2015 14:38:46 UTC] PHP   9. YMBESEO_Utils::get_plugin_name() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:172
[13-Dec-2015 14:38:46 UTC] PHP  10. get_plugin_data() /srv/www/example.com/current/web/app/plugins/ymbeseo/inc/class-ymbeseo-utils.php:790
[13-Dec-2015 14:38:46 UTC] PHP  11. get_file_data() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:84
[13-Dec-2015 14:38:46 UTC] PHP  12. fopen() /srv/www/example.com/current/web/wp/wp-includes/functions.php:4458

[13-Dec-2015 14:38:46 UTC] PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /srv/www/example.com/current/web/wp/wp-includes/functions.php on line 4461
[13-Dec-2015 14:38:46 UTC] PHP Stack trace:
[13-Dec-2015 14:38:46 UTC] PHP   1. {main}() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:0
[13-Dec-2015 14:38:46 UTC] PHP   2. require() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:16
[13-Dec-2015 14:38:46 UTC] PHP   3. activate_plugin() /srv/www/example.com/current/web/wp/wp-admin/plugins.php:42
[13-Dec-2015 14:38:46 UTC] PHP   4. do_action() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:572
[13-Dec-2015 14:38:46 UTC] PHP   5. call_user_func_array:{/srv/www/example.com/current/web/wp/wp-includes/plugin.php:525}() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   6. YMBESEO_Plugin_Conflict::hook_check_for_plugin_conflicts() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   7. Yoast_Plugin_Conflict->check_plugin_conflicts() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-plugin-conflict.php:143
[13-Dec-2015 14:38:46 UTC] PHP   8. Yoast_Plugin_Conflict->set_error() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:146
[13-Dec-2015 14:38:46 UTC] PHP   9. YMBESEO_Utils::get_plugin_name() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:172
[13-Dec-2015 14:38:46 UTC] PHP  10. get_plugin_data() /srv/www/example.com/current/web/app/plugins/ymbeseo/inc/class-ymbeseo-utils.php:790
[13-Dec-2015 14:38:46 UTC] PHP  11. get_file_data() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:84
[13-Dec-2015 14:38:46 UTC] PHP  12. fread() /srv/www/example.com/current/web/wp/wp-includes/functions.php:4461

[13-Dec-2015 14:38:46 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /srv/www/example.com/current/web/wp/wp-includes/functions.php on line 4464
[13-Dec-2015 14:38:46 UTC] PHP Stack trace:
[13-Dec-2015 14:38:46 UTC] PHP   1. {main}() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:0
[13-Dec-2015 14:38:46 UTC] PHP   2. require() /srv/www/example.com/current/web/wp/wp-admin/network/plugins.php:16
[13-Dec-2015 14:38:46 UTC] PHP   3. activate_plugin() /srv/www/example.com/current/web/wp/wp-admin/plugins.php:42
[13-Dec-2015 14:38:46 UTC] PHP   4. do_action() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:572
[13-Dec-2015 14:38:46 UTC] PHP   5. call_user_func_array:{/srv/www/example.com/current/web/wp/wp-includes/plugin.php:525}() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   6. YMBESEO_Plugin_Conflict::hook_check_for_plugin_conflicts() /srv/www/example.com/current/web/wp/wp-includes/plugin.php:525
[13-Dec-2015 14:38:46 UTC] PHP   7. Yoast_Plugin_Conflict->check_plugin_conflicts() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-plugin-conflict.php:143
[13-Dec-2015 14:38:46 UTC] PHP   8. Yoast_Plugin_Conflict->set_error() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:146
[13-Dec-2015 14:38:46 UTC] PHP   9. YMBESEO_Utils::get_plugin_name() /srv/www/example.com/current/web/app/plugins/ymbeseo/admin/class-yoast-plugin-conflict.php:172
[13-Dec-2015 14:38:46 UTC] PHP  10. get_plugin_data() /srv/www/example.com/current/web/app/plugins/ymbeseo/inc/class-ymbeseo-utils.php:790
[13-Dec-2015 14:38:46 UTC] PHP  11. get_file_data() /srv/www/example.com/current/web/wp/wp-admin/includes/plugin.php:84
[13-Dec-2015 14:38:46 UTC] PHP  12. fclose() /srv/www/example.com/current/web/wp/wp-includes/functions.php:4464
```

But like I said, both development and master branches do activate.

**Comment by QWp6t** [comment]
Oh, actually master won't activate for me anymore. I originally had my own fork activated, which was merged here. Must've been another commit that broke activation. But whatever. I'll just use development branch for now since it activates.

**Comment by senlin** [comment]
Hmmm, can't get either master nor development to activate

**Comment by senlin** [comment]
I tried both
`composer create-project senlin/ymbeseo:dev-master --prefer-source --keep-vcs` 
and 
`composer create-project senlin/ymbeseo:dev-development --prefer-source --keep-vcs`, 
but both result in an error message in my Terminal: 

```
  [InvalidArgumentException]                                      
  Could not find package senlin/ymbeseo with version dev-master.  
```

**Comment by robneu** [comment]
You shouldn't need to create a project as there's already a `composer.json` and `composer.lock` file stored in Git. Since the project is already intilized, running `composer install` within the plugin directory should be the only thing you need to do on the `development` branch.

The `master` branch was never working as far as I can tell. It was missing all the required `vendor` files from the get-go and this pull request was incorrect as it didn't include the PHP 5.2 autoloader or any of the (then necessary) 3rd party dependency files.

**Comment by senlin** [comment]
okay, maybe I have my environment completely wrong setup.

The master and development branches of this plugin (and all other plugins on Github) are residing in a folder called Sites/REPOs on my computer. 
 
I have a local dev site called Sites/testbed where I copy the files of the dev branch to.

Should I run the Repo straight from testbed instead or something?

**Comment by senlin** [comment]
> running composer install within the plugin directory 

Maybe a better explanation would be *running composer install* **within the ymbeseo folder** *of your local plugin directory* ?

Got it working now, phew...

**Comment by robneu** [comment]
You have a few options there. You could manage your development test site using composer and just add this plugin as a dependency and update it whenever the dev branch has new commits or a new version is released. I don't personally do that for stuff that's in ongoing development because it's too much of a hassle IMO. There might also be a way to symlink dev repos with composer... I'm not entirely sure. I know npm lets you do something like that.

What I do for things that are currently in development is I have all of my ongoing dev projects stored in one place and then they're symlinked into my various test sites. This should work fine if you use something like MAMP for local dev or if you use Vagrant with a provider other than Virtualbox. 

I use VMWare, so the symlinks created on my host machine carry through to the guest for me. Virtualbox didn't allow that last time I tried it, so my entire dev setup wouldn't work with Vagrant/VVV unless I switched providers. :\

You could also just continue doing what you're doing and manually copy files into your dev sites, but that seems like it would get really annoying after a while.

**Comment by senlin** [comment]
Thanks for your input and thought @robneu, much appreciated.

I'm not using MAMP or Vagrant or anything like that, I built an AMP stack instead.

Anyways, have it figured out and is working now, so will keep it like this for now :)

**Pull request merged**
